---
name: Ansible Eco vCenter Integration Test
on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  ansible_integration_test:
    runs-on: ["self-hosted", linux, X64]
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run-integration-on-vcenter'}}
    steps:
      - name: Extract pull request details
        id: extract_pr_details
        run: |
          pr_url="${{ github.event.issue.url }}"
          pr_details=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$pr_url")
          pr_commit_sha=$(echo "$pr_details" | jq -r '.pull_request.head.sha')
          echo "PR_COMMIT_SHA=$pr_commit_sha" >> $GITHUB_ENV

      - name: Create Check Run
        id: create_check_run
        run: |
          repo=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          pr_commit_sha="$PR_COMMIT_SHA"
          repo_owner=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)

          # Create check run using GitHub API
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo_owner/$repo/check-runs" \
            -d '{
              "name": "Ansible Eco vCenter Integration Test",
              "head_sha": "'"$pr_commit_sha"'",
              "status": "queued",
              "started_at": "'"$(date -u +"%FT%TZ")"'",
              "output": {
                "title": "Integration Test",
                "summary": "The integration test is in progress.",
                "text": "The integration test has been triggered. Check back later for the results."
              }
            }')

          # Extract check run ID
          check_run_id=$(echo "$response" | jq -r '.id')
          echo "CHECK_RUN_ID=$check_run_id" >> $GITHUB_ENV

      - name: print something
        run: |
           echo "hello"

      - name: Update Check Run Status
        if: always()
        run: |
          # Complete the check run using GitHub API
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo_owner/$repo/check-runs/$check_run_id" \
            -d '{
              "status": "completed",
              "completed_at": "'"$(date -u +"%FT%TZ")"'",
              "conclusion": "success",
              "output": {
                "title": "Integration Test",
                "summary": "The integration test has completed successfully.",
                "text": "The integration test has passed all checks."
              }
            }'
