# name: Molecule E2E Tests

# on:
#   push:
#     branches:
#       - provision_vm_test
#   pull_request:
#     branches:
#       - provision_vm_test
# # defaults:
# #  run:
# #   working-directory: "tests/e2e/molecule"

# jobs:
#   molecule:
#     runs-on: ubuntu-latest
#     strategy:
#     #   fail-fast: false
#       matrix:
#         scenario:
#           - provision_vm
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: provision_vm_test
#           path: .
#       - name: Install dependencies
#         run: |
#             python -m pip install --upgrade pip
#             pip install molecule[docker] ansible-lint yamllint ansible
#       - name: Install pyvmomi
#         run: pip install pyvmomi
#       - name: Set up vault password
#         run: |
#           echo "${{ secrets.VAULT_PASS }}" > vault.pass
#           echo "ANSIBLE_VAULT_PASSWORD_FILE=$(pwd)/vault.pass" >> $GITHUB_ENV
#       - name: Run Molecule tests
#         uses: gofrolist/molecule-action@v2
#         with:
#           molecule_command: test
#           molecule_args: --scenario-name ${{ matrix.scenario }}
#           molecule_working_dir: tests/e2e/
#         env:
#           ANSIBLE_FORCE_COLOR: '1'
      # - name: Cleanup
      #   uses: gofrolist/molecule-action@v2
      #   with:
      #     molecule_command: destroy
      #     molecule_args: --scenario-name ${{ matrix.scenario }}
      #     molecule_working_dir: tests/e2e/
      # - name: Remove e2e tests directory
      #   run: rm -rf tests/e2e/
